DROP TABLE IF EXISTS "InvoiceItem";
DROP TABLE IF EXISTS "Income";
DROP TABLE IF EXISTS "Invoice";
DROP TABLE IF EXISTS "Expense";
DROP TABLE IF EXISTS "TaxConfig";

DROP TYPE IF EXISTS "InvoiceStatus";
DROP TYPE IF EXISTS "IncomeStatus";
